apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  destination:
    namespace: home-assistants
    server: https://kubernetes.default.svc
  project: home-assistant
  source:
    path: home-assistant
    repoURL: https://github.com/kemosabe102/home-assistant
    targetRevision: HEAD