apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: home-assistant
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  source:
    chart: home-assistant
    repoURL: https://charts.pree.dev
    # latest targetRevision - https://github.com/pree/helm-charts/blob/master/charts/home-assistant/Chart.yaml
    targetRevision: 1.50.1
    helm:
      releaseName: home-assistant
      valuesObject:
        env:
          TZ: America/Los_Angeles
        # https://github.com/pajikos/home-assistant-helm-chart?tab=readme-ov-file#hostport-and-hostnetwork
        ingress:
          main:
            enabled: true
        persistence:
          config:
            enabled: true
        postgresql:
          enabled: true
        home-assistant:
          hardcodedValues:
            service:
              port: 80
            ingress:
              enabled: true
              annotations:
                kubernetes.io/ingress.class: "nginx"
                nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
                nginx.ingress.kubernetes.io/ssl-passthrough: "true"
              hosts:
                - host: home-assistant.local
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
  destination:
    namespace: home-assistant
    server: https://kubernetes.default.svc
