global:
  domain: argocd.local

configs:
  params:
    server.disable.auth: true
    server.insecure: true

  repositories:
    home-assistant:
      url: http://pajikos.github.io/home-assistant-helm-chart/
      name: pajikos
      type: helm
    prometheus:
      url: https://prometheus-community.github.io/helm-charts
      name: prometheus-community
      type: helm
    grafana:
      url: https://grafana.github.io/helm-charts
      name: grafana
      type: helm
    nginx:
      url: https://kubernetes.github.io/ingress-nginx
      name: ingress-nginx
      type: helm
  
controller:
  metrics:
    enabled: true
  serviceMonitor:
    enabled: true

certificate:
  enabled: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    tls: true
