apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: home-assistant
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    # latest targetRevision - https://artifacthub.io/packages/helm/prometheus-community/prometheus
    targetRevision: 25.29.0
    helm:
      releaseName: prometheus
      valuesObject:
        server:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: "nginx"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"  
            hosts:
              - prometheus.local
        prometheus-node-exporter:
          enabled: false
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
