apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: home-assistant
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    # latest targetRevision - https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
    targetRevision: 66.1.0
    helm:
      releaseName: kube-prometheus-stack
      valuesObject:
        grafana:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: "nginx"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"  
            hosts:
              - grafana.local
        prometheus:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: "nginx"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"  
            hosts:
              - prometheus.local
        nodeExporter:
          enabled: false
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
