# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: home-assistant
#   namespace: default
# spec:
#   project: default
#   source:
#     chart: home-assistant
#     repoURL: http://pajikos.github.io/home-assistant-helm-chart/
#     targetRevision: 0.2.86
#     helm:
#       releaseName: home-assistant
#       valuesObject:
#         hostNetwork: true
#         ingress:
#           enabled: true
#           className: nginx
#           annotations:
#             nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#             nginx.ingress.kubernetes.io/ssl-passthrough: "true"
#           hosts:
#             - host: home-assistant.local
#               paths:
#                 - path: /
#                   pathType: ImplementationSpecific
#         persistence:
#           enabled: true
#           size: 10Gi
#   destination:
#     server: "https://kubernetes.default.svc"
#     namespace: home-assistant

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassist-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: home-assistant
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: ha-apps
    repoURL: https://charts.pree.dev
    targetRevision: HEAD