apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  project: default
  source:
    chart: home-assistant
    repoURL: http://pajikos.github.io/home-assistant-helm-chart/
    helm:
      releaseName: home-assistant
      valuesObject:
        hostNetwork: true
        ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-passthrough: "true"
          hosts:
            - host: home-assistant.local
              paths:
                - path: /
                  pathType: ImplementationSpecific
    persistence:
      enabled: true
      size: 10Gi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: home-assistant